/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCitasRouteImport } from './routes/_authenticated/admin.citas'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminPacientesRouteImport } from './routes/_authenticated/admin.pacientes'
import { Route as AuthenticatedAdminTratamientosRouteImport } from './routes/_authenticated/admin.tratamientos'
import { Route as AuthenticatedAdminPacientesIdRouteImport } from './routes/_authenticated/admin.pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCitasRoute = AuthenticatedAdminCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacientesRoute =
  AuthenticatedAdminPacientesRouteImport.update({
    id: '/pacientes',
    path: '/pacientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTratamientosRoute =
  AuthenticatedAdminTratamientosRouteImport.update({
    id: '/tratamientos',
    path: '/tratamientos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacientesIdRoute =
  AuthenticatedAdminPacientesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPacientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/admin/citas': typeof AuthenticatedAdminCitasRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/pacientes': typeof AuthenticatedAdminPacientesRouteWithChildren
  '/admin/tratamientos': typeof AuthenticatedAdminTratamientosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pacientes/$id': typeof AuthenticatedAdminPacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/admin/citas': typeof AuthenticatedAdminCitasRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/pacientes': typeof AuthenticatedAdminPacientesRouteWithChildren
  '/admin/tratamientos': typeof AuthenticatedAdminTratamientosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pacientes/$id': typeof AuthenticatedAdminPacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/_authenticated/admin/citas': typeof AuthenticatedAdminCitasRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/pacientes': typeof AuthenticatedAdminPacientesRouteWithChildren
  '/_authenticated/admin/tratamientos': typeof AuthenticatedAdminTratamientosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pacientes/$id': typeof AuthenticatedAdminPacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/perfil'
    | '/api/whatsapp-webhook'
    | '/admin/citas'
    | '/admin/configuracion'
    | '/admin/pacientes'
    | '/admin/tratamientos'
    | '/admin/'
    | '/admin/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/perfil'
    | '/api/whatsapp-webhook'
    | '/admin/citas'
    | '/admin/configuracion'
    | '/admin/pacientes'
    | '/admin/tratamientos'
    | '/admin'
    | '/admin/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/api/whatsapp-webhook'
    | '/_authenticated/admin/citas'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/pacientes'
    | '/_authenticated/admin/tratamientos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/citas': {
      id: '/_authenticated/admin/citas'
      path: '/citas'
      fullPath: '/admin/citas'
      preLoaderRoute: typeof AuthenticatedAdminCitasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pacientes': {
      id: '/_authenticated/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AuthenticatedAdminPacientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tratamientos': {
      id: '/_authenticated/admin/tratamientos'
      path: '/tratamientos'
      fullPath: '/admin/tratamientos'
      preLoaderRoute: typeof AuthenticatedAdminTratamientosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pacientes/$id': {
      id: '/_authenticated/admin/pacientes/$id'
      path: '/$id'
      fullPath: '/admin/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminPacientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPacientesRoute
    }
  }
}

interface AuthenticatedAdminPacientesRouteChildren {
  AuthenticatedAdminPacientesIdRoute: typeof AuthenticatedAdminPacientesIdRoute
}

const AuthenticatedAdminPacientesRouteChildren: AuthenticatedAdminPacientesRouteChildren =
  {
    AuthenticatedAdminPacientesIdRoute: AuthenticatedAdminPacientesIdRoute,
  }

const AuthenticatedAdminPacientesRouteWithChildren =
  AuthenticatedAdminPacientesRoute._addFileChildren(
    AuthenticatedAdminPacientesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCitasRoute: typeof AuthenticatedAdminCitasRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminPacientesRoute: typeof AuthenticatedAdminPacientesRouteWithChildren
  AuthenticatedAdminTratamientosRoute: typeof AuthenticatedAdminTratamientosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCitasRoute: AuthenticatedAdminCitasRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminPacientesRoute:
    AuthenticatedAdminPacientesRouteWithChildren,
  AuthenticatedAdminTratamientosRoute: AuthenticatedAdminTratamientosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
